server:
  port: 8765

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: '$2a$12$j0en22/sNGB0.tFzA33Ma.bzUuDMQmGqfzjQ9chxWoqR.k7fsjbzS'
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - auth
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
